### ISSUE TITLE
能补充个插件如何使用的说明吗

### ISSUE THREAD

**Issue by elitepei** [seanliang/JavaPropertiesEditor#4]

**Comment by seanliang** [comment]
使用很简单：
1. 安装插件
2. 保险起见，重启Sublime Text
3. 打开java的properties文件，插件会将文件中的编码转换成文字以便查看
4. 修改properties文件并保存，插件会将文字转换成相应编码

你使用过程有出现什么问题么？

**Comment by elitepei** [comment]
File->Revert File 是可以将中文转换成Unicode码，建议在增加个功能将Unicode码在转换成中文
